# Generated by Django 4.2.26 on 2025-11-25 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_package_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': '客戶資料', 'verbose_name_plural': '客戶資料'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '帳單', 'verbose_name_plural': '帳單'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': '包裹', 'verbose_name_plural': '包裹'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': '服務類型', 'verbose_name_plural': '服務類型'},
        ),
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'verbose_name': '追蹤事件', 'verbose_name_plural': '追蹤事件'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.AddField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('MONTHLY', '月結帳單'), ('CASH', '現金支付'), ('CREDIT_CARD', '信用卡支付'), ('PREPAID', '預付 (由商家/第三方支付)')], default='CASH', max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_preference',
            field=models.CharField(choices=[('MONTHLY', '月結帳單'), ('COD', '貨到付款'), ('CASH', '現金支付'), ('CREDIT_CARD', '信用卡支付'), ('PREPAID', '預付')], default='CASH', max_length=20, verbose_name='帳單偏好'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_type',
            field=models.CharField(choices=[('CONTRACT', '合約客戶 (設有月結帳戶)'), ('NON_CONTRACT', '非合約客戶 (以現金或信用卡支付)'), ('PREPAID', '預付客戶 (貨運費用由商家或第三方支付)')], default='NON_CONTRACT', max_length=20, verbose_name='客戶類型'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='電話號碼'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customerprofile', verbose_name='客戶'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='計費週期結束'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='計費週期開始'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('OVERDUE', '逾期')], default='PENDING', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='package',
            name='dimensions',
            field=models.CharField(help_text='長x寬x高 (公分)', max_length=100, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='package',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='預計送達時間'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='易碎品'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_hazardous',
            field=models.BooleanField(default=False, verbose_name='危險物品'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_address',
            field=models.TextField(verbose_name='收件人地址'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(max_length=100, verbose_name='收件人姓名'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(max_length=20, verbose_name='收件人電話'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_packages', to=settings.AUTH_USER_MODEL, verbose_name='寄件人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicetype', verbose_name='服務類型'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', '已建立'), ('PICKED_UP', '已取件'), ('IN_TRANSIT', '運送中'), ('OUT_FOR_DELIVERY', '配送中'), ('DELIVERED', '已送達'), ('EXCEPTION', '異常')], default='CREATED', max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='追蹤號碼'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='重量 (公斤)', max_digits=6, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='基本價格'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='服務名稱'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='speed_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='速度倍率', max_digits=5, verbose_name='速度係數'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='weight_factor',
            field=models.DecimalField(decimal_places=2, help_text='每公斤價格', max_digits=5, verbose_name='重量係數'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='location',
            field=models.CharField(max_length=200, verbose_name='地點'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.package', verbose_name='包裹'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('CREATED', '已建立'), ('PICKED_UP', '已取件'), ('IN_TRANSIT', '運送中'), ('OUT_FOR_DELIVERY', '配送中'), ('DELIVERED', '已送達'), ('EXCEPTION', '異常')], max_length=20, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理員'), ('STAFF', '員工'), ('DRIVER', '司機'), ('CUSTOMER', '客戶')], default='CUSTOMER', max_length=20, verbose_name='角色'),
        ),
    ]
