# Generated by Django 4.2.26 on 2025-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customerprofile_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FLAT_ENVELOPE', 'Flat Envelope'), ('SMALL_BOX', 'Small Box'), ('MEDIUM_BOX', 'Medium Box'), ('LARGE_BOX', 'Large Box')], default='SMALL_BOX', max_length=20, verbose_name='包裹類型'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='delivery_speed',
            field=models.CharField(choices=[('OVERNIGHT', 'Overnight'), ('TWO_DAY', '2-Day Delivery'), ('STANDARD', 'Standard Express'), ('ECONOMY', 'Economy Express')], default='STANDARD', max_length=20, verbose_name='配送速度'),
        ),
    ]
