# Generated by Django 4.2.26 on 2025-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_package_package_type_servicetype_delivery_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FLAT_ENVELOPE', '扁平信封'), ('SMALL_BOX', '小型箱'), ('MEDIUM_BOX', '中型箱'), ('LARGE_BOX', '大型箱')], default='SMALL_BOX', max_length=20, verbose_name='包裹類型'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='delivery_speed',
            field=models.CharField(choices=[('OVERNIGHT', '隔夜送達'), ('TWO_DAY', '兩日送達'), ('STANDARD', '標準快遞'), ('ECONOMY', '經濟快遞')], default='STANDARD', max_length=20, verbose_name='配送速度'),
        ),
    ]
