# Generated by Django 4.2.26 on 2025-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_package_package_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='服務名稱'),
        ),
    ]
