# Generated by Django 4.2.26 on 2025-11-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicetype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profiles'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Service Type', 'verbose_name_plural': 'Service Types'},
        ),
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'verbose_name': 'Tracking Event', 'verbose_name_plural': 'Tracking Events'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='package',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Declared Value'),
        ),
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description of Contents'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='billing_preference',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Billing'), ('COD', 'Cash on Delivery'), ('CASH', 'Cash Payment'), ('CREDIT_CARD', 'Credit Card Payment'), ('PREPAID', 'Prepaid')], default='CASH', max_length=20, verbose_name='Billing Preference'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_type',
            field=models.CharField(choices=[('CONTRACT', 'Contract Customer (Monthly Account)'), ('NON_CONTRACT', 'Non-Contract Customer (Cash/Credit Card)'), ('PREPAID', 'Prepaid Customer (Merchant/Third Party)')], default='NON_CONTRACT', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customerprofile', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='package',
            name='dimensions',
            field=models.CharField(help_text='LxWxH (cm)', max_length=100, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='package',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Delivery'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Fragile'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_hazardous',
            field=models.BooleanField(default=False, verbose_name='Hazardous'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('FLAT_ENVELOPE', 'Flat Envelope'), ('SMALL_BOX', 'Small Box'), ('MEDIUM_BOX', 'Medium Box'), ('LARGE_BOX', 'Large Box')], default='SMALL_BOX', max_length=20, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='package',
            name='payment_method',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Billing'), ('CASH', 'Cash Payment'), ('CREDIT_CARD', 'Credit Card Payment'), ('PREPAID', 'Prepaid (Merchant/Third Party)')], default='CASH', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_address',
            field=models.TextField(verbose_name='Receiver Address'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(max_length=100, verbose_name='Receiver Name'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone',
            field=models.CharField(max_length=20, verbose_name='Receiver Phone'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_packages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicetype', verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception')], default='CREATED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_number',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight (kg)', max_digits=6, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='delivery_speed',
            field=models.CharField(choices=[('OVERNIGHT', 'Overnight Delivery'), ('TWO_DAY', 'Two-Day Delivery'), ('STANDARD', 'Standard Delivery'), ('ECONOMY', 'Economy Delivery')], default='STANDARD', max_length=20, verbose_name='Delivery Speed'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='speed_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Speed Multiplier', max_digits=5, verbose_name='Speed Factor'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='weight_factor',
            field=models.DecimalField(decimal_places=2, help_text='Price per kg', max_digits=5, verbose_name='Weight Factor'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.package', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DRIVER', 'Driver'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20, verbose_name='Role'),
        ),
    ]
