# Generated by Django 5.2.8 on 2025-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customerprofile_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='package',
            name='signed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Signed By'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('SORTING', 'Sorting'), ('HUB_TRANSFER', 'Hub Transfer'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception')], default='CREATED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('SORTING', 'Sorting'), ('HUB_TRANSFER', 'Hub Transfer'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('EXCEPTION', 'Exception')], max_length=20, verbose_name='Status'),
        ),
    ]
